import argparse
import json
import os
import re


def translate_diagram(files: list[str]):
    """
    Translates the files into a dbdiagram.io-friendly format
    """

    result = ""
    
    for file in files:
        if ".sql" not in file: continue
        with open(file, "r") as f:
            while line := f.readline():
                line = re.sub(r"CREATE TABLE( IF NOT EXISTS)?","TABLE",line,flags=re.IGNORECASE)
                line = re.sub(r"\(\s*$","{\n",line,flags=re.IGNORECASE)
                line = re.sub(r"^\)","}",line,flags=re.IGNORECASE)
                line = re.sub(r"\s*,","",line,flags=re.IGNORECASE)
                line = re.sub(r"^\s+(?P<col>\w+)\s+(?P<type>[\w\(\)]+)\s*(?P<args>.*)\s*",r"\t\1\t\2\t[\3]\n",line,flags=re.IGNORECASE)
                line = re.sub(r"PRIMARY KEY","PK,",line,flags=re.IGNORECASE)
                line = re.sub(r"GENERATED BY DEFAULT AS IDENTITY\s*","",line,flags=re.IGNORECASE) # Just ignore this case
                line = re.sub(r"DEFAULT '*([a-zA-Z_\(\)]+)'*",r"DEFAULT: '\1',",line,flags=re.IGNORECASE)
                line = re.sub(r"DEFAULT ([0-9]+)",r"DEFAULT: \1,",line,flags=re.IGNORECASE)
                line = re.sub(r"REFERENCES (\w+)\((\w*)\)",r"REF: - \1.\2, ",line,flags=re.IGNORECASE) # Default to 1-1
                line = re.sub(r"CHECK\s*\(.*\)",r"",line,flags=re.IGNORECASE)
                line = re.sub(r"NOT NULL",r"NOT NULL,",line,flags=re.IGNORECASE)
                line = re.sub(r"UNIQUE",r"UNIQUE,",line,flags=re.IGNORECASE)
                line = re.sub(r"\s*,\s*\]","]",line,flags=re.IGNORECASE)
                line = re.sub(r";","",line,flags=re.IGNORECASE)

                result += line
        result += "\n"
    return result


def translate_sql(files):
    """
    Translates the provided .sql files into the expected .json structure for ProtoGen
    """
    result = {}
    current_table = None

    for file in files:
        if ".sql" not in file: continue
        with open(file,"r") as f:
            while line := f.readline():
                if re.findall(";",line):
                    current_table = None
                if table_name := re.match(
                        r"CREATE TABLE(?: IF NOT EXISTS)? (?P<table_name>\w+)",
                        line, re.IGNORECASE
                    ):
                    module = table_name.group("table_name")
                    result[module] = {
                        "singular": module[:-1],
                        "object_name": re.sub( # Pascalize
                            r"([a-zA-Z])_([a-z])",
                            lambda x: x.group(1) + x.group(2).capitalize(),
                            re.sub(r"^([a-z])",lambda x: x.group().capitalize(), module)[:-1]
                        )
                    }
                    current_table = table_name.group("table_name")
                
                elif current_table:
                    if col := re.match(
                            r"^\s*(?P<column>[\w_]+)\s+(?P<type>[\w\(\)_]+)\s+(?P<args>.*)",
                            line, re.IGNORECASE
                        ):

                        attr = col.group("column")
                        typ = col.group("type")
                        args = col.group("args")
                        args = re.sub(r"\s*,*\s*$","",args)
                        
                        if re.findall(r"PRIMARY\s+KEY",args,re.IGNORECASE):
                            result[current_table]["pk"] = attr
                            args = re.sub(r"PRIMARY\s+KEY","",args,flags=re.IGNORECASE)

                        if not (attrs := result[current_table].get("attributes")):
                            attrs = result[current_table]["attributes"] = {}

                        attrs[attr] = {
                            "python_type": "Any",
                            "sql_type": typ,
                            "column_arguments": args
                        }

                        if "NOT NULL" in args.upper() and \
                            "DEFAULT" not in args.upper():
                            result[current_table]["attributes"][attr]["sample"] = \
                                f"[INSERT SAMPLE {col.group("column")} HERE]"  

    return json.dumps(result)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("dir",help="Input sql directory or file. Include the trailing \"/\" for directories.")
    sub = parser.add_subparsers(dest="command")

    sql = sub.add_parser("sql", help="Convert your .sql files to properly structured .json files. Sample data will have to be entered and orderings may need to be edited.")
    sql.set_defaults(func=translate_sql)
    
    dbdiagram = sub.add_parser("diagram", help="Convert your .sql files into a format that can be copy-pasted into dbdiagram.io.")
    dbdiagram.set_defaults(func=translate_diagram)

    args = parser.parse_args()


    is_dir = True
    try:
        ls = os.listdir(args.dir)
        
    except NotADirectoryError:
        is_dir = False
        ls = [args.dir]

    files = []
    for file in ls:
        if ".sql" not in file: continue
        files.append(os.path.join(os.path.dirname(__file__), f"{args.dir+"/" if is_dir else ""}{file}"))

    print(args.func(files))
